<?php

namespace Config;

use CodeIgniter\Router\RouteCollection;

/**
 * Auto-generated routes
 * 
 * This file contains routes that were automatically generated by the system
 * when a URI was accessed that didn't match any existing routes.
 */
function autoRoutes(RouteCollection $routes)
{
    // Auto-generated routes will be added here
    
    $routes->get('admin/siswa', 'Admin\\Siswa::index');
    $routes->get('admin/ruangan', 'Admin\\Ruangan::index');
    $routes->get('admin/ruangan/edit/(:num)', '\\App\\Controllers\\Admin\\Ruangan::edit/$1');
    $routes->get('admin/laporan/statistik', '\\App\\Controllers\\Admin\\Laporan::statistik');
    $routes->get('admin/laporan/export', '\\App\\Controllers\\Admin\\Laporan::export');
    $routes->get('admin/guru', '\\App\\Controllers\\Admin\\Guru::index');
}