<!DOCTYPE html>
<html>
<head>
    <title>Test Signature Table</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
        }
        .signature-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 40px;
        }
        .signature-cell {
            width: 45%;
            vertical-align: top;
        }
        .spacer-cell {
            width: 10%;
        }
    </style>
</head>
<body>
    <h1>Test Signature Table</h1>
    
    <p>This page demonstrates the signature table generated by the helper function.</p>
    
    <!-- Display the generated signature table -->
    <?= $signatureHtml ?>
</body>
</html>